#!/bin/bash
# file name preinst
# Pre-install script for imagec.


echo "Looking for old versions of imageC ..."

rm -rf /usr/local/bin/imagec
rm -rf /usr/local/bin/imagec_models
rm -rf /usr/local/bin/imagec_gui
