#ifndef __dialog_processing_controller__
#define __dialog_processing_controller__

/**
@file
Subclass of DialogProcessing, which is generated by wxFormBuilder.
*/

#include "backend/settings/analze_settings_parser.hpp"
#include "backend/settings/channel_settings.hpp"
#include "wxwidget.h"
namespace joda::ui::wxwidget {

//// end generated include

/** Implementing DialogProcessing */
class DialogProcessingController : public DialogProcessing
{
public:
  /** Constructor */
  DialogProcessingController(wxWindow *parent, const joda::settings::json::AnalyzeSettings &, wxWindowID id = wxID_ANY,
                             const wxString &title = _("Analyze running..."), const wxPoint &pos = wxDefaultPosition,
                             const wxSize &size = wxSize(694, 250), long style = wxDEFAULT_DIALOG_STYLE);
  //// end generated class members
};
}    // namespace joda::ui::wxwidget
#endif    // __dialog_processing_controller__
