#ifndef __dialog_processing_controller__
#define __dialog_processing_controller__

/**
@file
Subclass of DialogProcessing, which is generated by wxFormBuilder.
*/

#include <stdexcept>
#include "backend/settings/analze_settings_parser.hpp"
#include "backend/settings/channel_settings.hpp"
#include "controller/controller.hpp"
#include "wxwidget.h"
namespace joda::ui::wxwidget {

class DialogProcessingController : public DialogProcessing
{
public:
  /////////////////////////////////////////////////////
  DialogProcessingController(wxWindow *parent, joda::ctrl::Controller *pipelineController,
                             joda::settings::json::AnalyzeSettings *, wxWindowID id = wxID_ANY,
                             const wxString &title = _("Analyze running..."), const wxPoint &pos = wxDefaultPosition,
                             const wxSize &size = wxSize(694, 250), long style = wxDEFAULT_DIALOG_STYLE);
  ~DialogProcessingController();

private:
  /////////////////////////////////////////////////////
  void onStopClicked(wxCommandEvent &event) override;
  void onStartClicked(wxCommandEvent &event) override;
  void refreshFunction();

  /////////////////////////////////////////////////////
  joda::ctrl::Controller *mPipelineController;
  joda::settings::json::AnalyzeSettings *mAnalyzeSettins;
  std::shared_ptr<std::thread> mRefreshTimer;
  bool mStopped = false;
};
}    // namespace joda::ui::wxwidget
#endif    // __dialog_processing_controller__
