#ifndef __frame_main_controller__
#define __frame_main_controller__

/**
@file
Subclass of frameMain, which is generated by wxFormBuilder.
*/

#include <memory>
#include <thread>
#include <vector>
#include "backend/settings/pipeline_settings.hpp"
#include "controller/controller.hpp"
#include "ui/wxwidgets/panel_intersection_control.h"
#include "panel_channel_controller.h"
#include "wxwidget.h"

//// end generated include

namespace joda::ui::wxwidget {

class FrameMainController : public frameMain
{
public:
  /////////////////////////////////////////////////////
  FrameMainController(wxWindow *parent, joda::ctrl::Controller *pipelineController);
  ~FrameMainController();
  void addChannel();
  void removeChannel(int32_t channelIndex);
  void removeChannel(void *);
  void removeAllChannels();

  void addPipelineStep();
  void removePipelineStep(int32_t pipelineStepIndex);
  void removePipelineStep(void *);
  void removeAllPipelineSteps();
  auto getController() -> joda::ctrl::Controller *
  {
    return mPipelineController;
  }

private:
  /////////////////////////////////////////////////////
  static constexpr int PIPELINE_STEP_PANEL_INDEX_OFFSET = 1;

  /////////////////////////////////////////////////////
  void loadValues(const joda::settings::json::AnalyzeSettings &);
  nlohmann::json getValues();

  void onAddChannelClicked(wxCommandEvent &event) override;
  void onAddIntersectionClicked(wxCommandEvent &event) override;
  void onRunClicked(wxCommandEvent &event) override;
  void onAboutClicked(wxCommandEvent &event) override;
  void onCellChannelChoice(wxCommandEvent &event) override;
  void onWorkingDirChanged(wxFileDirPickerEvent &event) override;
  void onSaveSettingsClicked(wxCommandEvent &event) override;
  void onOpenSettingsClicked(wxCommandEvent &event) override;
  void refreshFunction();
  void showErrorDialog(const std::string &what);

  /////////////////////////////////////////////////////
  // Sync functions
  void syncSeries(int series);

  /////////////////////////////////////////////////////
  std::vector<std::shared_ptr<PanelChannelController>> mChannels;
  std::vector<std::shared_ptr<PanelIntersectionControl>> mIntersections;
  joda::ctrl::Controller *mPipelineController;
  std::shared_ptr<std::thread> mRefreshTimer;
  std::string mLastOpenedFolder;
  bool mStopped = false;
};
}    // namespace joda::ui::wxwidget
#endif    // __frame_main_controller__
