#ifndef __frame_main_controller__
#define __frame_main_controller__

/**
@file
Subclass of frameMain, which is generated by wxFormBuilder.
*/

#include <memory>
#include <vector>
#include "panel_channel_controller.h"
#include "wxwidget.h"

//// end generated include

namespace joda::ui::wxwidget {

class FrameMainController : public frameMain
{
public:
  /////////////////////////////////////////////////////
  FrameMainController(wxWindow *parent);
  void addChannel();
  void removeChannel();

private:
  /////////////////////////////////////////////////////
  void onAddChannelClicked(wxCommandEvent &event) override;

  /////////////////////////////////////////////////////
  std::vector<std::shared_ptr<PanelChannelController>> mChannels;
};
}    // namespace joda::ui::wxwidget
#endif    // __frame_main_controller__
