#ifndef __panel_cell_approx_controller__
#define __panel_cell_approx_controller__

/**
@file
Subclass of PanelCellApproximation, which is generated by wxFormBuilder.
*/

#include "backend/settings/pipeline_settings.hpp"
#include "ui/wxwidgets/panel_ui_pipelinestep.h"
#include "wxwidget.h"

namespace joda::ui::wxwidget {

class FrameMainController;

//// end generated include

/** Implementing PanelCellApproximation */
class PanelCellApproxController : public joda::ui::wxwidget::PanelCellApproximation, public PanelUiPipelineStep
{
public:
  /////////////////////////////////////////////////////
  PanelCellApproxController(FrameMainController *mainFrame, wxWindow *parent, wxWindowID id = wxID_ANY,
                            const wxPoint &pos = wxDefaultPosition, const wxSize &size = wxSize(-1, -1),
                            long style = wxTAB_TRAVERSAL, const wxString &name = wxEmptyString);

  void loadValues(const joda::settings::json::PipelineStepSettings &) override;
  void loadValues(const joda::settings::json::PipelineStepCellApproximation &);
  nlohmann::json getValues() override;
  uint64_t getUniqueID() override;

protected:
  /////////////////////////////////////////////////////
  FrameMainController *mMainFrame;

  void onRemoveClicked(wxCommandEvent &event);
  void onCellChannelChoice(wxCommandEvent &event) override;
  void OnPaint(wxPaintEvent &event);
};
}    // namespace joda::ui::wxwidget
#endif    // __panel_cell_approx_controller__
