name: Build and Push Multi-Platform Images

on:
  workflow_dispatch:   # <-- This enables manual trigger from GitHub UI

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Linux image
        run: |
          cd docker
          docker build -f Dockerfile.linux -t ${{ secrets.DOCKERHUB_USERNAME }}/imagec-dev:linux-latest .

      - name: Push Linux image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/imagec-dev:linux-latest

  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin


      - name: Build Windows image
        run: |
          cd docker
          docker build -f Dockerfile.windows -t ${{ secrets.DOCKERHUB_USERNAME }}/imagec-dev:windows-latest .

      - name: Push Windows image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/imagec-dev:windows-latest

  create-manifest:
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows]
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create and push multi-arch manifest
        run: |
          docker manifest create ${{ secrets.DOCKERHUB_USERNAME }}/imagec-dev:latest \
            ${{ secrets.DOCKERHUB_USERNAME }}/imagec-dev:linux-latest \
            ${{ secrets.DOCKERHUB_USERNAME }}/imagec-dev:windows-latest
          docker manifest push ${{ secrets.DOCKERHUB_USERNAME }}/imagec-dev:latest
