name: update-cache

on: workflow_dispatch

jobs:
  build-linux-cache:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check if cache exists
        run: |
          exit 0
          if [[ -d ".github/workflows/cache/conan-cache-${{ runner.os }}-v1" ]]; then
            echo "Cache exists, skipping"
            exit 0
          fi

      - name: Set up Conan
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Conan
        run: |
          sudo apt-get update
          sudo apt-get install -y libva-dev libvdpau-dev xkb-data
          sudo pip install conan
          sudo chmod 777 -R /root

      - name: Build cache
        run: |
          if [[ -f "/root/.conan2/profiles/default" ]]; then
            echo "Loaded from cache"
          else
            sudo conan profile detect
          fi
          sudo cat /root/.conan2/profiles/default
          sudo conan install . --profile conan/profile_linux --output-folder=build --build=missing
          sudo chmod 777 -R /root/.conan2

      - name: Save Conan Cache
        uses: actions/cache/save@v4
        with:
          path: /root/.conan2
          key: conan-cache-${{ runner.os }}-v1


  build-macos-cache:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Check if cache exists
        run: |
          exit 0
          if [[ -d ".github/workflows/cache/conan-cache-${{ runner.os }}-v1" ]]; then
            echo "Cache exists, skipping"
            exit 0
          fi
      
      - name: Set up Conan
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Conan
        run: |
          pip install conan

      - name: Build with Conan
        run: |
          if [[ -f "/Users/runner/.conan2/profiles/default" ]]; then
            echo "Loaded from cache"
          else
            conan profile detect
          fi
          cat /Users/runner/.conan2/profiles/default
          conan install . --profile conan/profile_macos --output-folder=build --build=missing

      - name: Save Conan Cache
        uses: actions/cache/save@v4
        with:
          path: /Users/runner/.conan2
          key: conan-cache-${{ runner.os }}-v1


  build-windows-cache:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check if cache exists
        run: |
          if (Test-Path ".github\workflows\cache\conan-cache-Windows-v1") {
            Write-Host "Cache exists, skipping"
            exit 0
          }

      - name: Set up Conan
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Conan
        run: |
          pip install conan

      - name: Build with Conan
        run: |
    
          New-Item -Path "C:\Users\runneradmin\.conan2\profiles" -ItemType Directory -Force
          Copy-Item -Path "$env:GITHUB_WORKSPACE\conan\profile_win_mingw" -Destination "C:\Users\runneradmin\.conan2\profiles\default"

          cd "$env:GITHUB_WORKSPACE/conan/patches/onnx"
          ./patch.ps1
          cd "$env:GITHUB_WORKSPACE"

          ls "C:\Users\runneradmin\.conan2\p"
          ls "C:\Users\runneradmin\.conan2\p\onnx305a97e88c569\s"
          ls "C:\Users\runneradmin\.conan2\p\onnx305a97e88c569"
          conan install . --profile $env:GITHUB_WORKSPACE\conan\profile_win_mingw --output-folder=build --build=missing
          ls "C:\Users\runneradmin\.conan2\p\b"



      - name: Save Conan Cache
        uses: actions/cache/save@v4
        with:
          path: C:/Users/runneradmin/.conan2
          key: conan-cache-${{ runner.os }}-v1
